use std::{
    io::{self, Read, Write},
    net::{Shutdown, TcpStream},
    sync::mpsc::{self, Receiver, Sender},
    thread,
};

/// An event reported by one side of the LSP relay.
#[derive(Debug)]
pub enum RelayEvent {
    /// The editor closed the adapter's standard input.
    StdinClosed,

    /// The TCP peer closed the connection.
    SocketClosed,

    /// One side of the relay failed.
    Error {
        direction: &'static str,
        error: io::Error,
    },
}

/// A running bidirectional relay.
///
/// The worker threads notify the supervisor through `events`. Calling
/// `shutdown` interrupts socket reads and writes. A thread blocked on the
/// process's stdin cannot be interrupted portably, but it does not prevent
/// process termination after the main thread returns.
pub struct Relay {
    control_stream: TcpStream,
    events: Receiver<RelayEvent>,
}

impl Relay {
    /// Start relaying process stdin to the TCP socket and the TCP socket to
    /// process stdout.
    pub fn start(stream: TcpStream) -> io::Result<Self> {
        stream.set_nonblocking(false)?;
        stream.set_nodelay(true)?;

        let socket_reader = stream.try_clone()?;
        let socket_writer = stream.try_clone()?;
        let control_stream = stream;

        let (event_sender, event_receiver) = mpsc::channel();

        start_stdin_to_socket(socket_writer, event_sender.clone());
        start_socket_to_stdout(socket_reader, event_sender);

        Ok(Self {
            control_stream,
            events: event_receiver,
        })
    }

    /// Receives events generated by the relay workers.
    pub fn events(&self) -> &Receiver<RelayEvent> {
        &self.events
    }

    /// Interrupts both directions of the TCP relay.
    pub fn shutdown(&self) {
        match self.control_stream.shutdown(Shutdown::Both) {
            Ok(()) => {}

            Err(error)
                if matches!(
                    error.kind(),
                    io::ErrorKind::NotConnected | io::ErrorKind::BrokenPipe
                ) => {}

            Err(error) => {
                eprintln!(
                    "tool4d-lsp-stdio: failed to close the LSP socket: \
                     {error}"
                );
            }
        }
    }
}

fn start_stdin_to_socket(mut socket_writer: TcpStream, event_sender: Sender<RelayEvent>) {
    thread::spawn(move || {
        let result = (|| -> io::Result<()> {
            let stdin = io::stdin();
            let mut stdin = stdin.lock();

            io::copy(&mut stdin, &mut socket_writer)?;

            match socket_writer.shutdown(Shutdown::Write) {
                Ok(()) => {}

                Err(error)
                    if matches!(
                        error.kind(),
                        io::ErrorKind::NotConnected | io::ErrorKind::BrokenPipe
                    ) => {}

                Err(error) => return Err(error),
            }

            Ok(())
        })();

        let event = match result {
            Ok(()) => RelayEvent::StdinClosed,

            Err(error) => RelayEvent::Error {
                direction: "stdin-to-socket",
                error,
            },
        };

        let _ = event_sender.send(event);
    });
}

fn start_socket_to_stdout(mut socket_reader: TcpStream, event_sender: Sender<RelayEvent>) {
    thread::spawn(move || {
        let result = (|| -> io::Result<()> {
            let stdout = io::stdout();
            let mut stdout = stdout.lock();

            io::copy(&mut socket_reader, &mut stdout)?;
            stdout.flush()
        })();

        let event = match result {
            Ok(()) => RelayEvent::SocketClosed,

            Err(error) => RelayEvent::Error {
                direction: "socket-to-stdout",
                error,
            },
        };

        let _ = event_sender.send(event);
    });
}

/// Relays arbitrary input and output streams to a TCP connection.
///
/// This is useful for integration tests that should not use the test
/// process's actual standard input and standard output.
pub fn streams_to_tcp<R, W>(mut input: R, mut output: W, stream: TcpStream) -> io::Result<()>
where
    R: Read + Send + 'static,
    W: Write,
{
    stream.set_nonblocking(false)?;
    stream.set_nodelay(true)?;

    let mut socket_reader = stream.try_clone()?;
    let mut socket_writer = stream;

    thread::spawn(move || {
        let _ = io::copy(&mut input, &mut socket_writer);
        let _ = socket_writer.shutdown(Shutdown::Write);
    });

    io::copy(&mut socket_reader, &mut output)?;
    output.flush()
}
